# Project Compiler Options

# FORCE / ENABLE C++14

SET(CMAKE_CXX_STANDARD 17)
SET(CMAKE_CXX_STANDARD_REQUIRED ON)
SET(CMAKE_CXX_EXTENSIONS OFF)

# COMPILER FLAGS

#SET(CMAKE_CXX_FLAGS "-Wall -Wextra -pedantic")
#SET(CMAKE_CXX_FLAGS_DEBUG "-g")
#SET(CMAKE_CXX_FLAGS_RELEASE "-Os -march=native")
